{% set name = "xorg-libICE" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: 974e4ed414225eb3c716985df9709f4da8d22a67a2890066bc6dfc89ad298625
  patches:
    - time.patch

build:
  number: 1
  # xorg-libxdmcp, libxcb, libx11 aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-util-macros ==1.20.2
    - xorg-xtrans ==1.6.0

test:
  commands:
    - test -f $PREFIX/lib/libICE.dylib  # [osx]
    - test -f $PREFIX/lib/libICE.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libice
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libice
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org Inter-Client Exchange library.
  description: |
    The X.org Inter-Client Exchange library.

extra:
  recipe-maintainers:
    - pkgw
